---
#-------------------------------
# General Site Settings

title: Con Vịt Software
logo:
author: TB
description: Mobile Consulting & Mobile Apps
email: tim@email.com
#phone: 
address: Leek, Staffordshire, UK | Sài Gòn, VN
copyright: Copyright &copy; 2024

menu:
  - { name: About, link: "/about" }
  - { name: Blog, link: "/blog" }
  - { name: Portfolio, link: "/portfolio" }
  - { name: Contact, link: "/contact" }

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

google-analytics: # UA-XXXXXX-X

#-------------------------------
# Comment Section (Disqus)

disqus-identifier: # Add your shortname for Disqus Comment. For example mr-brown

#-------------------------------
# Hero Section

hero:
  hero-title: Hi! I’m <br> Tim, <br> iOS Developer

social:
  - { icon: "ti-linkedin", link: "https://www.linkedin.com/in/tim-belfield-8a516b47/" }
#  - { icon: "ti-instagram", link: "#" }
#  - { icon: "ti-dribbble", link: "#" }
#  - { icon: "ti-twitter", link: "#" }

#-------------------------------
# About (Section and Page)

# About Section
blurb: I make Software for the mobile ecosystem with a focus on quality and usability. Developing my own products and projects alongside providing consulting for companies looking to ensure they have a great app store footprint. Developing apps for a decade plus in a variety of industries and settings, with millions of users touching software I wrote.

blurb-btn-link: "/about"
blurb-btn-name: About Me

# About Page

# Work Process Section
work-process:
  - title: "Research and Plan"
    icon: "assets/images/icons/plan.png"
    content: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."

  - title: "Design and Develop"
    icon: "assets/images/icons/design.png"
    content: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."

  - title: "Deliver"
    icon: "assets/images/icons/print.png"
    content: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."

# My Team Section
team:
  - title: "Jack Schenziwe"
    image: "assets/images/team/member-1.png"
    designation: "Project Manager"

  - title: "Julias Carlie"
    image: "assets/images/team/member-2.png"
    designation: "Web Developer"

  - title: "John Doe"
    image: "assets/images/team/member-3.png"
    designation: "Designer"

#-------------------------------
# Skills Section

#skills-title: Skills
#skills:
#  - { name: Web Design, color: "#fdb157", value: "90%" }
#  - { name: Logo Design, color: "#9473e6", value: "60%" }
#  - { name: After Effects, color: "#bdecf6", value: "80%" }
#  - { name: Web App, color: "#ffbcaa", value: "70%" }

#-------------------------------
# Experience Section

experience-title: Experience
experience:
  - {
      name: Senior iOS Developer,
      icon: "icon-3.png",
      date: "Sept 2018 - Apr 2021",
      organization: "Ready2Order GmbH",
    }
  - {
      name: Senior iOS Developer,
      icon: "icon-2.png",
      date: "May 2021 - Oct 2022",
      organization: "Rendity GmbH",
    }
  - {
      name: Senior iOS Developer,
      icon: "icon-1.png",
      date: "Nov 2022 - Apr 2024",
      organization: "Flutter Interactive Plc",
  }

#-------------------------------
# Education Section

education-title: Education
education:
  - {
      name: MSci & BSc Hons Computer Science,
      date: "2012",
      organization: "The University of Nottingham",
    }

#-------------------------------
# Services Section

services-title: Services
services:
  - {
      name: Co-Founding,
      icon: ti-palette,
      description: "I am open to joining a group of co-founders who are looking for a technically skilled engineer to bring an existing idea to market. I can provide the engineering skills required for a fantastic mobile first experience. Contact me below",
      active: ,# Add true to select section
    }
  - {
      name: App Development (Full time),
      icon: ti-vector,
      description: "I am available for full time app development on pre-existing and greenfield apps either in a team setting or as an individual. Contract lengths of 3 months and up will be considered. I can provide mentoring and support to enable your current team to succeed.",
      active: true, # Add true to select section
    }
  - {
      name: App Development (Part time),
      icon: ti-panel,
      description: "Got a small app or an existing app that needs to be maintained? I will be able to assist in this on a part time continuous basis. Please enquire below.",
      active: ,# Add true to select section
    }

#-------------------------------
# Portfolio (Section and Page)

# Portfolio Home Section
portfolio-home-items:
  - image: "assets/images/portfolio/item-1.png"
    url: "#"

  - image: "assets/images/portfolio/item-2.png"
    url: "#"

  - image: "assets/images/portfolio/item-3.png"
    url: "#"

  - image: "assets/images/portfolio/item-4.png"
    url: "#"

  - image: "assets/images/portfolio/item-5.png"
    url: "#"

# Portfolio Page
portfolio-label:
  - { title: "UI/UX Design", type: "design" }
  - { title: "BRANDING", type: "branding" }
  - { title: "ILLUSTRATION", type: "illustration" }

portfolio-items:
  - image: "assets/images/portfolio/item-1.png"
    url: "#"
    portfolio-type:
      - type: "design"
      - type: "illustration"

  - image: "assets/images/portfolio/item-2.png"
    url: "#"
    portfolio-type:
      - type: "branding"

  - image: "assets/images/portfolio/item-3.png"
    url: "#"
    portfolio-type:
      - type: "illustration"

  - image: "assets/images/portfolio/item-6.png"
    url: "#"
    portfolio-type:
      - type: "design"
      - type: "branding"

  - image: "assets/images/portfolio/item-8.png"
    url: "#"
    portfolio-type:
      - type: "illustration"

  - image: "assets/images/portfolio/item-5.png"
    url: "#"
    portfolio-type:
      - type: "design"

  - image: "assets/images/portfolio/item-1.png"
    url: "#"
    portfolio-type:
      - type: "branding"

  - image: "assets/images/portfolio/item-3.png"
    url: "#"
    portfolio-type:
      - type: "design"
      - type: "illustration"
      - type: "branding"

  - image: "assets/images/portfolio/item-7.png"
    url: "#"
    portfolio-type:
      - type: "illustration"

#-------------------------------
# Testimonials Section

#testimonial-items:
#  - name: "Jesica Gomez"
#    image: "assets/images/testimonial/client-1.png"
#    designation: "CEO, Funder"
#    content: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, <strong>quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</strong> Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur."
#
#  - name: "Jesica Gomez"
#    image: "assets/images/testimonial/client-1.png"
#    content: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, <strong>quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</strong> Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur."
#    designation: "CEO, Funder"
#
#  - name: "Jesica Gomez"
#    image: "assets/images/testimonial/client-1.png"
#    designation: "CEO, Funder"
#    content: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, <strong>quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</strong> Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur."

#-------------------------------
# Client Slider Section
#
#client-slider-items:
#  - logo: "assets/images/clients-logo/client-logo-1.png"
#    url: "#"
#
#  - logo: "assets/images/clients-logo/client-logo-2.png"
#    url: "#"
#
#  - logo: "assets/images/clients-logo/client-logo-3.png"
#    url: "#"
#
#  - logo: "assets/images/clients-logo/client-logo-4.png"
#    url: "#"
#
#  - logo: "assets/images/clients-logo/client-logo-5.png"
#    url: "#"
#
#  - logo: "assets/images/clients-logo/client-logo-1.png"
#    url: "#"
#
#  - logo: "assets/images/clients-logo/client-logo-2.png"
#    url: "#"
#
#  - logo: "assets/images/clients-logo/client-logo-3.png"
#    url: "#"
#
#  - logo: "assets/images/clients-logo/client-logo-4.png"
#    url: "#"
#
#  - logo: "assets/images/clients-logo/client-logo-5.png"
#    url: "#"
#
#-------------------------------
# Contact Section

contact-title: Contact Info
contact-email: steve.fruits@email.com
